name: Check for a new lunch menu
on:
  push
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install xmllint
        run: sudo apt-get install --no-install-recommends -y libxml2-utils
      - run: ./run.sh
